class AnimeServices {
  constructor() {
    this.url = '';
    this.animes = [
      {
        mal_id: 5114,
        url: 'https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood',
        images: {
          jpg: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1223/96541.jpg',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1223/96541t.jpg',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1223/96541l.jpg',
          },
          webp: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1223/96541.webp',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1223/96541t.webp',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1223/96541l.webp',
          },
        },
        trailer: {
          youtube_id: '--IcmZkvL0Q',
          url: 'https://www.youtube.com/watch?v=--IcmZkvL0Q',
          embed_url: 'https://www.youtube.com/embed/--IcmZkvL0Q?enablejsapi=1&wmode=opaque&autoplay=1',
          images: {
            image_url: 'https://img.youtube.com/vi/--IcmZkvL0Q/default.jpg',
            small_image_url: 'https://img.youtube.com/vi/--IcmZkvL0Q/sddefault.jpg',
            medium_image_url: 'https://img.youtube.com/vi/--IcmZkvL0Q/mqdefault.jpg',
            large_image_url: 'https://img.youtube.com/vi/--IcmZkvL0Q/hqdefault.jpg',
            maximum_image_url: 'https://img.youtube.com/vi/--IcmZkvL0Q/maxresdefault.jpg',
          },
        },
        title: 'Fullmetal Alchemist: Brotherhood',
        title_english: 'Fullmetal Alchemist: Brotherhood',
        title_japanese: '鋼の錬金術師 FULLMETAL ALCHEMIST',
        title_synonyms: [
          'Hagane no Renkinjutsushi: Fullmetal Alchemist',
          'Fullmetal Alchemist (2009)',
          'FMA',
          'FMAB',
        ],
        type: 'TV',
        source: 'Manga',
        episodes: 64,
        status: 'Finished Airing',
        airing: false,
        aired: {
          from: '2009-04-05T00:00:00+00:00',
          to: '2010-07-04T00:00:00+00:00',
          prop: {
            from: {
              day: 5,
              month: 4,
              year: 2009,
            },
            to: {
              day: 4,
              month: 7,
              year: 2010,
            },
          },
          string: 'Apr 5, 2009 to Jul 4, 2010',
        },
        duration: '24 min per ep',
        rating: 'R - 17+ (violence & profanity)',
        score: 9.14,
        scored_by: 1828024,
        rank: 1,
        popularity: 3,
        members: 2867035,
        favorites: 200612,
        synopsis: "After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality. Ignoring the alchemical principle banning human transmutation, the boys attempted to bring their recently deceased mother back to life. Instead, they suffered brutal personal loss: Alphonse's body disintegrated while Edward lost a leg and then sacrificed an arm to keep Alphonse's soul in the physical realm by binding it to a hulking suit of armor. The brothers are rescued by their neighbor Pinako Rockbell and her granddaughter Winry. Known as a bio-mechanical engineering prodigy, Winry creates prosthetic limbs for Edward by utilizing \"automail,\" a tough, versatile metal used in robots and combat armor. After years of training, the Elric brothers set off on a quest to restore their bodies by locating the Philosopher's Stone—a powerful gem that allows an alchemist to defy the traditional laws of Equivalent Exchange. As Edward becomes an infamous alchemist and gains the nickname \"Fullmetal,\" the boys' journey embroils them in a growing conspiracy that threatens the fate of the world. [Written by MAL Rewrite]",
        background: null,
        season: 'spring',
        year: 2009,
        broadcast: {
          day: 'Sundays',
          time: '17:00',
          timezone: 'Asia/Tokyo',
          string: 'Sundays at 17:00 (JST)',
        },
        producers: [
          {
            mal_id: 17,
            type: 'anime',
            name: 'Aniplex',
            url: 'https://myanimelist.net/anime/producer/17/Aniplex',
          },
          {
            mal_id: 58,
            type: 'anime',
            name: 'Square Enix',
            url: 'https://myanimelist.net/anime/producer/58/Square_Enix',
          },
          {
            mal_id: 143,
            type: 'anime',
            name: 'Mainichi Broadcasting System',
            url: 'https://myanimelist.net/anime/producer/143/Mainichi_Broadcasting_System',
          },
          {
            mal_id: 1155,
            type: 'anime',
            name: 'Studio Moriken',
            url: 'https://myanimelist.net/anime/producer/1155/Studio_Moriken',
          },
        ],
        licensors: [
          {
            mal_id: 102,
            type: 'anime',
            name: 'Funimation',
            url: 'https://myanimelist.net/anime/producer/102/Funimation',
          },
          {
            mal_id: 493,
            type: 'anime',
            name: 'Aniplex of America',
            url: 'https://myanimelist.net/anime/producer/493/Aniplex_of_America',
          },
        ],
        studios: [
          {
            mal_id: 4,
            type: 'anime',
            name: 'Bones',
            url: 'https://myanimelist.net/anime/producer/4/Bones',
          },
        ],
        genres: [
          {
            mal_id: 1,
            type: 'anime',
            name: 'Action',
            url: 'https://myanimelist.net/anime/genre/1/Action',
          },
          {
            mal_id: 2,
            type: 'anime',
            name: 'Adventure',
            url: 'https://myanimelist.net/anime/genre/2/Adventure',
          },
          {
            mal_id: 8,
            type: 'anime',
            name: 'Drama',
            url: 'https://myanimelist.net/anime/genre/8/Drama',
          },
          {
            mal_id: 10,
            type: 'anime',
            name: 'Fantasy',
            url: 'https://myanimelist.net/anime/genre/10/Fantasy',
          },
        ],
        explicit_genres: [],
        themes: [
          {
            mal_id: 38,
            type: 'anime',
            name: 'Military',
            url: 'https://myanimelist.net/anime/genre/38/Military',
          },
        ],
        demographics: [
          {
            mal_id: 27,
            type: 'anime',
            name: 'Shounen',
            url: 'https://myanimelist.net/anime/genre/27/Shounen',
          },
        ],
      },
      {
        mal_id: 50265,
        url: 'https://myanimelist.net/anime/50265/Spy_x_Family',
        images: {
          jpg: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795.jpg',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795t.jpg',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795l.jpg',
          },
          webp: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795.webp',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795t.webp',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795l.webp',
          },
        },
        trailer: {
          youtube_id: 'ofXigq9aIpo',
          url: 'https://www.youtube.com/watch?v=ofXigq9aIpo',
          embed_url: 'https://www.youtube.com/embed/ofXigq9aIpo?enablejsapi=1&wmode=opaque&autoplay=1',
          images: {
            image_url: 'https://img.youtube.com/vi/ofXigq9aIpo/default.jpg',
            small_image_url: 'https://img.youtube.com/vi/ofXigq9aIpo/sddefault.jpg',
            medium_image_url: 'https://img.youtube.com/vi/ofXigq9aIpo/mqdefault.jpg',
            large_image_url: 'https://img.youtube.com/vi/ofXigq9aIpo/hqdefault.jpg',
            maximum_image_url: 'https://img.youtube.com/vi/ofXigq9aIpo/maxresdefault.jpg',
          },
        },
        title: 'Spy x Family',
        title_english: null,
        title_japanese: 'SPY×FAMILY',
        title_synonyms: [],
        type: 'TV',
        source: 'Manga',
        episodes: 12,
        status: 'Currently Airing',
        airing: true,
        aired: {
          from: '2022-04-09T00:00:00+00:00',
          to: null,
          prop: {
            from: {
              day: 9,
              month: 4,
              year: 2022,
            },
            to: {
              day: null,
              month: null,
              year: null,
            },
          },
          string: 'Apr 9, 2022 to ?',
        },
        duration: '24 min per ep',
        rating: 'PG-13 - Teens 13 or older',
        score: 9.09,
        scored_by: 175321,
        rank: 2,
        popularity: 256,
        members: 631302,
        favorites: 16122,
        synopsis: "For the agent known as \"Twilight,\" no order is too tall if it is for the sake of peace. Operating as Westalis' master spy, Twilight works tirelessly to prevent extremists from sparking a war with neighboring country Ostania. For his latest mission, he must investigate Ostanian politician, Donovan Desmond, by infiltrating his son's school: the prestigious Eden Academy. Thus, the agent faces the most difficult task of his career: get married, have a child, and play family. Twilight, or \"Loid Forger,\" quickly adopts the unassuming orphan Anya to play the role of a six-year-old daughter and prospective Eden Academy student. For a wife, he comes across Yor Briar, an absent-minded office worker who needs a pretend partner of her own to impress her friends. However, Loid is not the only one with a hidden nature. Yor moonlights as the lethal assassin \"Thorn Princess.\" For her, marrying Loid creates the perfect cover. Meanwhile, Anya is not the ordinary girl she appears to be; she is an esper, the product of secret experiments that allow her to read minds. Although she uncovers their true identities, Anya is thrilled that her new parents are cool secret agents! She would never tell them, of course. That would ruin the fun. Under the guise of \"The Forgers,\" the spy, the assassin, and the esper must act as a family while carrying out their own agendas. Although these liars and misfits are only playing parts, they soon find that family is about far more than blood relations. [Written by MAL Rewrite]",
        background: null,
        season: 'spring',
        year: 2022,
        broadcast: {
          day: 'Saturdays',
          time: '23:00',
          timezone: 'Asia/Tokyo',
          string: 'Saturdays at 23:00 (JST)',
        },
        producers: [
          {
            mal_id: 16,
            type: 'anime',
            name: 'TV Tokyo',
            url: 'https://myanimelist.net/anime/producer/16/TV_Tokyo',
          },
          {
            mal_id: 62,
            type: 'anime',
            name: 'Shogakukan-Shueisha Productions',
            url: 'https://myanimelist.net/anime/producer/62/Shogakukan-Shueisha_Productions',
          },
          {
            mal_id: 1143,
            type: 'anime',
            name: 'TOHO animation',
            url: 'https://myanimelist.net/anime/producer/1143/TOHO_animation',
          },
          {
            mal_id: 1365,
            type: 'anime',
            name: 'Shueisha',
            url: 'https://myanimelist.net/anime/producer/1365/Shueisha',
          },
        ],
        licensors: [],
        studios: [
          {
            mal_id: 858,
            type: 'anime',
            name: 'Wit Studio',
            url: 'https://myanimelist.net/anime/producer/858/Wit_Studio',
          },
          {
            mal_id: 1835,
            type: 'anime',
            name: 'CloverWorks',
            url: 'https://myanimelist.net/anime/producer/1835/CloverWorks',
          },
        ],
        genres: [
          {
            mal_id: 1,
            type: 'anime',
            name: 'Action',
            url: 'https://myanimelist.net/anime/genre/1/Action',
          },
          {
            mal_id: 4,
            type: 'anime',
            name: 'Comedy',
            url: 'https://myanimelist.net/anime/genre/4/Comedy',
          },
        ],
        explicit_genres: [],
        themes: [
          {
            mal_id: 53,
            type: 'anime',
            name: 'Childcare',
            url: 'https://myanimelist.net/anime/genre/53/Childcare',
          },
        ],
        demographics: [
          {
            mal_id: 27,
            type: 'anime',
            name: 'Shounen',
            url: 'https://myanimelist.net/anime/genre/27/Shounen',
          },
        ],
      },
      {
        mal_id: 28977,
        url: 'https://myanimelist.net/anime/28977/Gintama°',
        images: {
          jpg: {
            image_url: 'https://cdn.myanimelist.net/images/anime/3/72078.jpg',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/3/72078t.jpg',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/3/72078l.jpg',
          },
          webp: {
            image_url: 'https://cdn.myanimelist.net/images/anime/3/72078.webp',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/3/72078t.webp',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/3/72078l.webp',
          },
        },
        trailer: {
          youtube_id: null,
          url: null,
          embed_url: null,
          images: {
            image_url: null,
            small_image_url: null,
            medium_image_url: null,
            large_image_url: null,
            maximum_image_url: null,
          },
        },
        title: 'Gintama°',
        title_english: 'Gintama Season 4',
        title_japanese: '銀魂°',
        title_synonyms: [
          "Gintama' (2015)",
        ],
        type: 'TV',
        source: 'Manga',
        episodes: 51,
        status: 'Finished Airing',
        airing: false,
        aired: {
          from: '2015-04-08T00:00:00+00:00',
          to: '2016-03-30T00:00:00+00:00',
          prop: {
            from: {
              day: 8,
              month: 4,
              year: 2015,
            },
            to: {
              day: 30,
              month: 3,
              year: 2016,
            },
          },
          string: 'Apr 8, 2015 to Mar 30, 2016',
        },
        duration: '24 min per ep',
        rating: 'PG-13 - Teens 13 or older',
        score: 9.08,
        scored_by: 212232,
        rank: 2,
        popularity: 338,
        members: 529993,
        favorites: 14156,
        synopsis: "Gintoki, Shinpachi, and Kagura return as the fun-loving but broke members of the Yorozuya team! Living in an alternate-reality Edo, where swords are prohibited and alien overlords have conquered Japan, they try to thrive on doing whatever work they can get their hands on. However, Shinpachi and Kagura still haven't been paid... Does Gin-chan really spend all that cash playing pachinko? Meanwhile, when Gintoki drunkenly staggers home one night, an alien spaceship crashes nearby. A fatally injured crew member emerges from the ship and gives Gintoki a strange, clock-shaped device, warning him that it is incredibly powerful and must be safeguarded. Mistaking it for his alarm clock, Gintoki proceeds to smash the device the next morning and suddenly discovers that the world outside his apartment has come to a standstill. With Kagura and Shinpachi at his side, he sets off to get the device fixed; though, as usual, nothing is ever that simple for the Yorozuya team. Filled with tongue-in-cheek humor and moments of heartfelt emotion, Gintama's fourth season finds Gintoki and his friends facing both their most hilarious misadventures and most dangerous crises yet. [Written by MAL Rewrite]",
        background: 'This is a fourth season of Gintama. In the episode continuity corresponds to episodes 266-316 of Gintama.',
        season: 'spring',
        year: 2015,
        broadcast: {
          day: 'Wednesdays',
          time: '18:00',
          timezone: 'Asia/Tokyo',
          string: 'Wednesdays at 18:00 (JST)',
        },
        producers: [
          {
            mal_id: 16,
            type: 'anime',
            name: 'TV Tokyo',
            url: 'https://myanimelist.net/anime/producer/16/TV_Tokyo',
          },
          {
            mal_id: 17,
            type: 'anime',
            name: 'Aniplex',
            url: 'https://myanimelist.net/anime/producer/17/Aniplex',
          },
          {
            mal_id: 53,
            type: 'anime',
            name: 'Dentsu',
            url: 'https://myanimelist.net/anime/producer/53/Dentsu',
          },
        ],
        licensors: [
          {
            mal_id: 102,
            type: 'anime',
            name: 'Funimation',
            url: 'https://myanimelist.net/anime/producer/102/Funimation',
          },
          {
            mal_id: 1468,
            type: 'anime',
            name: 'Crunchyroll',
            url: 'https://myanimelist.net/anime/producer/1468/Crunchyroll',
          },
        ],
        studios: [
          {
            mal_id: 1258,
            type: 'anime',
            name: 'Bandai Namco Pictures',
            url: 'https://myanimelist.net/anime/producer/1258/Bandai_Namco_Pictures',
          },
        ],
        genres: [
          {
            mal_id: 1,
            type: 'anime',
            name: 'Action',
            url: 'https://myanimelist.net/anime/genre/1/Action',
          },
          {
            mal_id: 4,
            type: 'anime',
            name: 'Comedy',
            url: 'https://myanimelist.net/anime/genre/4/Comedy',
          },
          {
            mal_id: 24,
            type: 'anime',
            name: 'Sci-Fi',
            url: 'https://myanimelist.net/anime/genre/24/Sci-Fi',
          },
        ],
        explicit_genres: [],
        themes: [
          {
            mal_id: 57,
            type: 'anime',
            name: 'Gag Humor',
            url: 'https://myanimelist.net/anime/genre/57/Gag_Humor',
          },
          {
            mal_id: 13,
            type: 'anime',
            name: 'Historical',
            url: 'https://myanimelist.net/anime/genre/13/Historical',
          },
          {
            mal_id: 20,
            type: 'anime',
            name: 'Parody',
            url: 'https://myanimelist.net/anime/genre/20/Parody',
          },
          {
            mal_id: 21,
            type: 'anime',
            name: 'Samurai',
            url: 'https://myanimelist.net/anime/genre/21/Samurai',
          },
        ],
        demographics: [
          {
            mal_id: 27,
            type: 'anime',
            name: 'Shounen',
            url: 'https://myanimelist.net/anime/genre/27/Shounen',
          },
        ],
      },
      {
        mal_id: 38524,
        url: 'https://myanimelist.net/anime/38524/Shingeki_no_Kyojin_Season_3_Part_2',
        images: {
          jpg: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1517/100633.jpg',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1517/100633t.jpg',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1517/100633l.jpg',
          },
          webp: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1517/100633.webp',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1517/100633t.webp',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1517/100633l.webp',
          },
        },
        trailer: {
          youtube_id: 'hKHepjfj5Tw',
          url: 'https://www.youtube.com/watch?v=hKHepjfj5Tw',
          embed_url: 'https://www.youtube.com/embed/hKHepjfj5Tw?enablejsapi=1&wmode=opaque&autoplay=1',
          images: {
            image_url: 'https://img.youtube.com/vi/hKHepjfj5Tw/default.jpg',
            small_image_url: 'https://img.youtube.com/vi/hKHepjfj5Tw/sddefault.jpg',
            medium_image_url: 'https://img.youtube.com/vi/hKHepjfj5Tw/mqdefault.jpg',
            large_image_url: 'https://img.youtube.com/vi/hKHepjfj5Tw/hqdefault.jpg',
            maximum_image_url: 'https://img.youtube.com/vi/hKHepjfj5Tw/maxresdefault.jpg',
          },
        },
        title: 'Shingeki no Kyojin Season 3 Part 2',
        title_english: 'Attack on Titan Season 3 Part 2',
        title_japanese: '進撃の巨人 Season3 Part.2',
        title_synonyms: [],
        type: 'TV',
        source: 'Manga',
        episodes: 10,
        status: 'Finished Airing',
        airing: false,
        aired: {
          from: '2019-04-29T00:00:00+00:00',
          to: '2019-07-01T00:00:00+00:00',
          prop: {
            from: {
              day: 29,
              month: 4,
              year: 2019,
            },
            to: {
              day: 1,
              month: 7,
              year: 2019,
            },
          },
          string: 'Apr 29, 2019 to Jul 1, 2019',
        },
        duration: '23 min per ep',
        rating: 'R - 17+ (violence & profanity)',
        score: 9.08,
        scored_by: 1285134,
        rank: 3,
        popularity: 31,
        members: 1819958,
        favorites: 50569,
        synopsis: "Seeking to restore humanity's diminishing hope, the Survey Corps embark on a mission to retake Wall Maria, where the battle against the merciless \"Titans\" takes the stage once again. Returning to the tattered Shiganshina District that was once his home, Eren Yeager and the Corps find the town oddly unoccupied by Titans. Even after the outer gate is plugged, they strangely encounter no opposition. The mission progresses smoothly until Armin Arlert, highly suspicious of the enemy's absence, discovers distressing signs of a potential scheme against them. Shingeki no Kyojin Season 3 Part 2 follows Eren as he vows to take back everything that was once his. Alongside him, the Survey Corps strive—through countless sacrifices—to carve a path towards victory and uncover the secrets locked away in the Yeager family's basement. [Written by MAL Rewrite]",
        background: "Shingeki no Kyojin adapts content from volumes 18-22 of Hajime Isayama's award-winning manga of the same name.",
        season: 'spring',
        year: 2019,
        broadcast: {
          day: 'Mondays',
          time: '00:10',
          timezone: 'Asia/Tokyo',
          string: 'Mondays at 00:10 (JST)',
        },
        producers: [
          {
            mal_id: 10,
            type: 'anime',
            name: 'Production I.G',
            url: 'https://myanimelist.net/anime/producer/10/Production_IG',
          },
          {
            mal_id: 53,
            type: 'anime',
            name: 'Dentsu',
            url: 'https://myanimelist.net/anime/producer/53/Dentsu',
          },
          {
            mal_id: 143,
            type: 'anime',
            name: 'Mainichi Broadcasting System',
            url: 'https://myanimelist.net/anime/producer/143/Mainichi_Broadcasting_System',
          },
          {
            mal_id: 144,
            type: 'anime',
            name: 'Pony Canyon',
            url: 'https://myanimelist.net/anime/producer/144/Pony_Canyon',
          },
          {
            mal_id: 159,
            type: 'anime',
            name: 'Kodansha',
            url: 'https://myanimelist.net/anime/producer/159/Kodansha',
          },
          {
            mal_id: 1499,
            type: 'anime',
            name: 'Techno Sound',
            url: 'https://myanimelist.net/anime/producer/1499/Techno_Sound',
          },
          {
            mal_id: 1557,
            type: 'anime',
            name: 'Pony Canyon Enterprise',
            url: 'https://myanimelist.net/anime/producer/1557/Pony_Canyon_Enterprise',
          },
        ],
        licensors: [
          {
            mal_id: 102,
            type: 'anime',
            name: 'Funimation',
            url: 'https://myanimelist.net/anime/producer/102/Funimation',
          },
        ],
        studios: [
          {
            mal_id: 858,
            type: 'anime',
            name: 'Wit Studio',
            url: 'https://myanimelist.net/anime/producer/858/Wit_Studio',
          },
        ],
        genres: [
          {
            mal_id: 1,
            type: 'anime',
            name: 'Action',
            url: 'https://myanimelist.net/anime/genre/1/Action',
          },
          {
            mal_id: 8,
            type: 'anime',
            name: 'Drama',
            url: 'https://myanimelist.net/anime/genre/8/Drama',
          },
        ],
        explicit_genres: [],
        themes: [
          {
            mal_id: 58,
            type: 'anime',
            name: 'Gore',
            url: 'https://myanimelist.net/anime/genre/58/Gore',
          },
          {
            mal_id: 38,
            type: 'anime',
            name: 'Military',
            url: 'https://myanimelist.net/anime/genre/38/Military',
          },
          {
            mal_id: 76,
            type: 'anime',
            name: 'Survival',
            url: 'https://myanimelist.net/anime/genre/76/Survival',
          },
        ],
        demographics: [
          {
            mal_id: 27,
            type: 'anime',
            name: 'Shounen',
            url: 'https://myanimelist.net/anime/genre/27/Shounen',
          },
        ],
      },
      {
        mal_id: 9253,
        url: 'https://myanimelist.net/anime/9253/Steins_Gate',
        images: {
          jpg: {
            image_url: 'https://cdn.myanimelist.net/images/anime/5/73199.jpg',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/5/73199t.jpg',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/5/73199l.jpg',
          },
          webp: {
            image_url: 'https://cdn.myanimelist.net/images/anime/5/73199.webp',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/5/73199t.webp',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/5/73199l.webp',
          },
        },
        trailer: {
          youtube_id: '27OZc-ku6is',
          url: 'https://www.youtube.com/watch?v=27OZc-ku6is',
          embed_url: 'https://www.youtube.com/embed/27OZc-ku6is?enablejsapi=1&wmode=opaque&autoplay=1',
          images: {
            image_url: 'https://img.youtube.com/vi/27OZc-ku6is/default.jpg',
            small_image_url: 'https://img.youtube.com/vi/27OZc-ku6is/sddefault.jpg',
            medium_image_url: 'https://img.youtube.com/vi/27OZc-ku6is/mqdefault.jpg',
            large_image_url: 'https://img.youtube.com/vi/27OZc-ku6is/hqdefault.jpg',
            maximum_image_url: 'https://img.youtube.com/vi/27OZc-ku6is/maxresdefault.jpg',
          },
        },
        title: 'Steins;Gate',
        title_english: 'Steins;Gate',
        title_japanese: 'STEINS;GATE',
        title_synonyms: [],
        type: 'TV',
        source: 'Visual novel',
        episodes: 24,
        status: 'Finished Airing',
        airing: false,
        aired: {
          from: '2011-04-06T00:00:00+00:00',
          to: '2011-09-14T00:00:00+00:00',
          prop: {
            from: {
              day: 6,
              month: 4,
              year: 2011,
            },
            to: {
              day: 14,
              month: 9,
              year: 2011,
            },
          },
          string: 'Apr 6, 2011 to Sep 14, 2011',
        },
        duration: '24 min per ep',
        rating: 'PG-13 - Teens 13 or older',
        score: 9.08,
        scored_by: 1228041,
        rank: 5,
        popularity: 13,
        members: 2225172,
        favorites: 169769,
        synopsis: "Eccentric scientist Rintarou Okabe has a never-ending thirst for scientific exploration. Together with his ditzy but well-meaning friend Mayuri Shiina and his roommate Itaru Hashida, Rintarou founds the Future Gadget Laboratory in the hopes of creating technological innovations that baffle the human psyche. Despite claims of grandeur, the only notable \"gadget\" the trio have created is a microwave that has the mystifying power to turn bananas into green goo. However, when Rintarou decides to attend neuroscientist Kurisu Makise's conference on time travel, he experiences a series of strange events that lead him to believe that there is more to the \"Phone Microwave\" gadget than meets the eye. Apparently able to send text messages into the past using the microwave, Rintarou dabbles further with the \"time machine,\" attracting the ire and attention of the mysterious organization SERN. Due to the novel discovery, Rintarou and his friends find themselves in an ever-present danger. As he works to mitigate the damage his invention has caused to the timeline, he is not only fighting a battle to save his loved ones, but also one against his degrading sanity. [Written by MAL Rewrite]",
        background: "Steins;Gate is based on 5pb. and Nitroplus' released in 2009.",
        season: 'spring',
        year: 2011,
        broadcast: {
          day: 'Wednesdays',
          time: '02:05',
          timezone: 'Asia/Tokyo',
          string: 'Wednesdays at 02:05 (JST)',
        },
        producers: [
          {
            mal_id: 61,
            type: 'anime',
            name: 'Frontier Works',
            url: 'https://myanimelist.net/anime/producer/61/Frontier_Works',
          },
          {
            mal_id: 108,
            type: 'anime',
            name: 'Media Factory',
            url: 'https://myanimelist.net/anime/producer/108/Media_Factory',
          },
          {
            mal_id: 166,
            type: 'anime',
            name: 'Movic',
            url: 'https://myanimelist.net/anime/producer/166/Movic',
          },
          {
            mal_id: 238,
            type: 'anime',
            name: 'AT-X',
            url: 'https://myanimelist.net/anime/producer/238/AT-X',
          },
          {
            mal_id: 352,
            type: 'anime',
            name: 'Kadokawa Pictures Japan',
            url: 'https://myanimelist.net/anime/producer/352/Kadokawa_Pictures_Japan',
          },
          {
            mal_id: 459,
            type: 'anime',
            name: 'Nitroplus',
            url: 'https://myanimelist.net/anime/producer/459/Nitroplus',
          },
        ],
        licensors: [
          {
            mal_id: 102,
            type: 'anime',
            name: 'Funimation',
            url: 'https://myanimelist.net/anime/producer/102/Funimation',
          },
        ],
        studios: [
          {
            mal_id: 314,
            type: 'anime',
            name: 'White Fox',
            url: 'https://myanimelist.net/anime/producer/314/White_Fox',
          },
        ],
        genres: [
          {
            mal_id: 8,
            type: 'anime',
            name: 'Drama',
            url: 'https://myanimelist.net/anime/genre/8/Drama',
          },
          {
            mal_id: 24,
            type: 'anime',
            name: 'Sci-Fi',
            url: 'https://myanimelist.net/anime/genre/24/Sci-Fi',
          },
          {
            mal_id: 41,
            type: 'anime',
            name: 'Suspense',
            url: 'https://myanimelist.net/anime/genre/41/Suspense',
          },
        ],
        explicit_genres: [],
        themes: [
          {
            mal_id: 40,
            type: 'anime',
            name: 'Psychological',
            url: 'https://myanimelist.net/anime/genre/40/Psychological',
          },
          {
            mal_id: 78,
            type: 'anime',
            name: 'Time Travel',
            url: 'https://myanimelist.net/anime/genre/78/Time_Travel',
          },
        ],
        demographics: [],
      },
      {
        mal_id: 9969,
        url: 'https://myanimelist.net/anime/9969/Gintama',
        images: {
          jpg: {
            image_url: 'https://cdn.myanimelist.net/images/anime/4/50361.jpg',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/4/50361t.jpg',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/4/50361l.jpg',
          },
          webp: {
            image_url: 'https://cdn.myanimelist.net/images/anime/4/50361.webp',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/4/50361t.webp',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/4/50361l.webp',
          },
        },
        trailer: {
          youtube_id: null,
          url: null,
          embed_url: null,
          images: {
            image_url: null,
            small_image_url: null,
            medium_image_url: null,
            large_image_url: null,
            maximum_image_url: null,
          },
        },
        title: "Gintama'",
        title_english: 'Gintama Season 2',
        title_japanese: "銀魂'",
        title_synonyms: [
          'Gintama (2011)',
        ],
        type: 'TV',
        source: 'Manga',
        episodes: 51,
        status: 'Finished Airing',
        airing: false,
        aired: {
          from: '2011-04-04T00:00:00+00:00',
          to: '2012-03-26T00:00:00+00:00',
          prop: {
            from: {
              day: 4,
              month: 4,
              year: 2011,
            },
            to: {
              day: 26,
              month: 3,
              year: 2012,
            },
          },
          string: 'Apr 4, 2011 to Mar 26, 2012',
        },
        duration: '24 min per ep',
        rating: 'PG-13 - Teens 13 or older',
        score: 9.05,
        scored_by: 205703,
        rank: 6,
        popularity: 382,
        members: 467404,
        favorites: 6960,
        synopsis: "After a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya members, have become completely different characters! Fleeing from the Yorozuya headquarters in confusion, Shinpachi finds that all the denizens of Edo have undergone impossibly extreme changes, in both appearance and personality. Most unbelievably, his sister Otae has married the Shinsengumi chief and shameless stalker Isao Kondou and is pregnant with their first child. Bewildered, Shinpachi agrees to join the Shinsengumi at Otae and Kondou's request and finds even more startling transformations afoot both in and out of the ranks of the the organization. However, discovering that Vice Chief Toushirou Hijikata has remained unchanged, Shinpachi and his unlikely Shinsengumi ally set out to return the city of Edo to how they remember it. With even more dirty jokes, tongue-in-cheek parodies, and shameless references, Gintama' follows the Yorozuya team through more of their misadventures in the vibrant, alien-filled world of Edo. [Written by MAL Rewrite]",
        background: 'This is the second season of Gintama. In the episode continuity corresponds to episodes 202-252 of Gintama.',
        season: 'spring',
        year: 2011,
        broadcast: {
          day: 'Mondays',
          time: '18:00',
          timezone: 'Asia/Tokyo',
          string: 'Mondays at 18:00 (JST)',
        },
        producers: [
          {
            mal_id: 16,
            type: 'anime',
            name: 'TV Tokyo',
            url: 'https://myanimelist.net/anime/producer/16/TV_Tokyo',
          },
          {
            mal_id: 17,
            type: 'anime',
            name: 'Aniplex',
            url: 'https://myanimelist.net/anime/producer/17/Aniplex',
          },
          {
            mal_id: 53,
            type: 'anime',
            name: 'Dentsu',
            url: 'https://myanimelist.net/anime/producer/53/Dentsu',
          },
          {
            mal_id: 643,
            type: 'anime',
            name: 'Trinity Sound',
            url: 'https://myanimelist.net/anime/producer/643/Trinity_Sound',
          },
          {
            mal_id: 763,
            type: 'anime',
            name: 'Miracle Robo',
            url: 'https://myanimelist.net/anime/producer/763/Miracle_Robo',
          },
          {
            mal_id: 829,
            type: 'anime',
            name: 'Studio Jack',
            url: 'https://myanimelist.net/anime/producer/829/Studio_Jack',
          },
          {
            mal_id: 1365,
            type: 'anime',
            name: 'Shueisha',
            url: 'https://myanimelist.net/anime/producer/1365/Shueisha',
          },
        ],
        licensors: [],
        studios: [
          {
            mal_id: 14,
            type: 'anime',
            name: 'Sunrise',
            url: 'https://myanimelist.net/anime/producer/14/Sunrise',
          },
        ],
        genres: [
          {
            mal_id: 1,
            type: 'anime',
            name: 'Action',
            url: 'https://myanimelist.net/anime/genre/1/Action',
          },
          {
            mal_id: 4,
            type: 'anime',
            name: 'Comedy',
            url: 'https://myanimelist.net/anime/genre/4/Comedy',
          },
          {
            mal_id: 24,
            type: 'anime',
            name: 'Sci-Fi',
            url: 'https://myanimelist.net/anime/genre/24/Sci-Fi',
          },
        ],
        explicit_genres: [],
        themes: [
          {
            mal_id: 57,
            type: 'anime',
            name: 'Gag Humor',
            url: 'https://myanimelist.net/anime/genre/57/Gag_Humor',
          },
          {
            mal_id: 13,
            type: 'anime',
            name: 'Historical',
            url: 'https://myanimelist.net/anime/genre/13/Historical',
          },
          {
            mal_id: 20,
            type: 'anime',
            name: 'Parody',
            url: 'https://myanimelist.net/anime/genre/20/Parody',
          },
          {
            mal_id: 21,
            type: 'anime',
            name: 'Samurai',
            url: 'https://myanimelist.net/anime/genre/21/Samurai',
          },
        ],
        demographics: [
          {
            mal_id: 27,
            type: 'anime',
            name: 'Shounen',
            url: 'https://myanimelist.net/anime/genre/27/Shounen',
          },
        ],
      },
      {
        mal_id: 39486,
        url: 'https://myanimelist.net/anime/39486/Gintama__The_Final',
        images: {
          jpg: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1988/113791.jpg',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1988/113791t.jpg',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1988/113791l.jpg',
          },
          webp: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1988/113791.webp',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1988/113791t.webp',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1988/113791l.webp',
          },
        },
        trailer: {
          youtube_id: 'Zn1filVUyf8',
          url: 'https://www.youtube.com/watch?v=Zn1filVUyf8',
          embed_url: 'https://www.youtube.com/embed/Zn1filVUyf8?enablejsapi=1&wmode=opaque&autoplay=1',
          images: {
            image_url: 'https://img.youtube.com/vi/Zn1filVUyf8/default.jpg',
            small_image_url: 'https://img.youtube.com/vi/Zn1filVUyf8/sddefault.jpg',
            medium_image_url: 'https://img.youtube.com/vi/Zn1filVUyf8/mqdefault.jpg',
            large_image_url: 'https://img.youtube.com/vi/Zn1filVUyf8/hqdefault.jpg',
            maximum_image_url: 'https://img.youtube.com/vi/Zn1filVUyf8/maxresdefault.jpg',
          },
        },
        title: 'Gintama: The Final',
        title_english: 'Gintama: The Very Final',
        title_japanese: '銀魂 THE FINAL',
        title_synonyms: [],
        type: 'Movie',
        source: 'Manga',
        episodes: 1,
        status: 'Finished Airing',
        airing: false,
        aired: {
          from: '2021-01-08T00:00:00+00:00',
          to: null,
          prop: {
            from: {
              day: 8,
              month: 1,
              year: 2021,
            },
            to: {
              day: null,
              month: null,
              year: null,
            },
          },
          string: 'Jan 8, 2021',
        },
        duration: '1 hr 44 min',
        rating: 'PG-13 - Teens 13 or older',
        score: 9.05,
        scored_by: 47608,
        rank: 7,
        popularity: 1735,
        members: 100481,
        favorites: 3428,
        synopsis: "Two years have passed following the Tendoshuu's invasion of the O-Edo Central Terminal. Since then, the Yorozuya have gone their separate ways. Foreseeing Utsuro's return, Gintoki Sakata begins surveying Earth's ley lines for traces of the other man's Altana. After an encounter with the remnants of the Tendoshuu—who continue to press on in search of immortality—Gintoki returns to Edo. Later, the regrouped Shinsengumi and Yorozuya begin an attack on the occupied Central Terminal. With the Altana harvested by the wreckage of the Tendoshuu's ship in danger of detonating, the Yorozuya and their allies fight their enemies while the safety of Edo—and the rest of the world—hangs in the balance. Fulfilling the wishes of their teacher, Shouyou Yoshida's former students unite and relive their pasts one final time in an attempt to save their futures. [Written by MAL Rewrite]",
        background: 'As of March 2021, Gintama: The Final has earned a franchise record of 1.85 billion yen (16.94 million USD) and debuted at No. 1 at the Japanese box office. The film concludes the Gintama anime series, adapting chapters 699-704 of the original manga with new story elements.',
        season: null,
        year: null,
        broadcast: {
          day: null,
          time: null,
          timezone: null,
          string: null,
        },
        producers: [
          {
            mal_id: 16,
            type: 'anime',
            name: 'TV Tokyo',
            url: 'https://myanimelist.net/anime/producer/16/TV_Tokyo',
          },
          {
            mal_id: 415,
            type: 'anime',
            name: 'Warner Bros. Japan',
            url: 'https://myanimelist.net/anime/producer/415/Warner_Bros_Japan',
          },
        ],
        licensors: [
          {
            mal_id: 531,
            type: 'anime',
            name: 'Eleven Arts',
            url: 'https://myanimelist.net/anime/producer/531/Eleven_Arts',
          },
        ],
        studios: [
          {
            mal_id: 1258,
            type: 'anime',
            name: 'Bandai Namco Pictures',
            url: 'https://myanimelist.net/anime/producer/1258/Bandai_Namco_Pictures',
          },
        ],
        genres: [
          {
            mal_id: 1,
            type: 'anime',
            name: 'Action',
            url: 'https://myanimelist.net/anime/genre/1/Action',
          },
          {
            mal_id: 4,
            type: 'anime',
            name: 'Comedy',
            url: 'https://myanimelist.net/anime/genre/4/Comedy',
          },
          {
            mal_id: 8,
            type: 'anime',
            name: 'Drama',
            url: 'https://myanimelist.net/anime/genre/8/Drama',
          },
          {
            mal_id: 24,
            type: 'anime',
            name: 'Sci-Fi',
            url: 'https://myanimelist.net/anime/genre/24/Sci-Fi',
          },
        ],
        explicit_genres: [],
        themes: [
          {
            mal_id: 57,
            type: 'anime',
            name: 'Gag Humor',
            url: 'https://myanimelist.net/anime/genre/57/Gag_Humor',
          },
          {
            mal_id: 13,
            type: 'anime',
            name: 'Historical',
            url: 'https://myanimelist.net/anime/genre/13/Historical',
          },
          {
            mal_id: 20,
            type: 'anime',
            name: 'Parody',
            url: 'https://myanimelist.net/anime/genre/20/Parody',
          },
          {
            mal_id: 21,
            type: 'anime',
            name: 'Samurai',
            url: 'https://myanimelist.net/anime/genre/21/Samurai',
          },
        ],
        demographics: [
          {
            mal_id: 27,
            type: 'anime',
            name: 'Shounen',
            url: 'https://myanimelist.net/anime/genre/27/Shounen',
          },
        ],
      },
      {
        mal_id: 11061,
        url: 'https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011',
        images: {
          jpg: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013t.jpg',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg',
          },
          webp: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013.webp',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013t.webp',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013l.webp',
          },
        },
        trailer: {
          youtube_id: 'D9iTQRB4XRk',
          url: 'https://www.youtube.com/watch?v=D9iTQRB4XRk',
          embed_url: 'https://www.youtube.com/embed/D9iTQRB4XRk?enablejsapi=1&wmode=opaque&autoplay=1',
          images: {
            image_url: 'https://img.youtube.com/vi/D9iTQRB4XRk/default.jpg',
            small_image_url: 'https://img.youtube.com/vi/D9iTQRB4XRk/sddefault.jpg',
            medium_image_url: 'https://img.youtube.com/vi/D9iTQRB4XRk/mqdefault.jpg',
            large_image_url: 'https://img.youtube.com/vi/D9iTQRB4XRk/hqdefault.jpg',
            maximum_image_url: 'https://img.youtube.com/vi/D9iTQRB4XRk/maxresdefault.jpg',
          },
        },
        title: 'Hunter x Hunter (2011)',
        title_english: 'Hunter x Hunter',
        title_japanese: 'HUNTER×HUNTER（ハンター×ハンター）',
        title_synonyms: [
          'HxH (2011)',
        ],
        type: 'TV',
        source: 'Manga',
        episodes: 148,
        status: 'Finished Airing',
        airing: false,
        aired: {
          from: '2011-10-02T00:00:00+00:00',
          to: '2014-09-24T00:00:00+00:00',
          prop: {
            from: {
              day: 2,
              month: 10,
              year: 2011,
            },
            to: {
              day: 24,
              month: 9,
              year: 2014,
            },
          },
          string: 'Oct 2, 2011 to Sep 24, 2014',
        },
        duration: '23 min per ep',
        rating: 'PG-13 - Teens 13 or older',
        score: 9.05,
        scored_by: 1465250,
        rank: 8,
        popularity: 10,
        members: 2350869,
        favorites: 179794,
        synopsis: "Hunters devote themselves to accomplishing hazardous tasks, all from traversing the world's uncharted territories to locating rare items and monsters. Before becoming a Hunter, one must pass the Hunter Examination—a high-risk selection process in which most applicants end up handicapped or worse, deceased. Ambitious participants who challenge the notorious exam carry their own reason. What drives 12-year-old Gon Freecss is finding Ging, his father and a Hunter himself. Believing that he will meet his father by becoming a Hunter, Gon takes the first step to walk the same path. During the Hunter Examination, Gon befriends the medical student Leorio Paladiknight, the vindictive Kurapika, and ex-assassin Killua Zoldyck. While their motives vastly differ from each other, they band together for a common goal and begin to venture into a perilous world. [Written by MAL Rewrite]",
        background: null,
        season: 'fall',
        year: 2011,
        broadcast: {
          day: 'Sundays',
          time: '10:55',
          timezone: 'Asia/Tokyo',
          string: 'Sundays at 10:55 (JST)',
        },
        producers: [
          {
            mal_id: 29,
            type: 'anime',
            name: 'VAP',
            url: 'https://myanimelist.net/anime/producer/29/VAP',
          },
          {
            mal_id: 1003,
            type: 'anime',
            name: 'Nippon Television Network',
            url: 'https://myanimelist.net/anime/producer/1003/Nippon_Television_Network',
          },
          {
            mal_id: 1365,
            type: 'anime',
            name: 'Shueisha',
            url: 'https://myanimelist.net/anime/producer/1365/Shueisha',
          },
        ],
        licensors: [
          {
            mal_id: 119,
            type: 'anime',
            name: 'VIZ Media',
            url: 'https://myanimelist.net/anime/producer/119/VIZ_Media',
          },
        ],
        studios: [
          {
            mal_id: 11,
            type: 'anime',
            name: 'Madhouse',
            url: 'https://myanimelist.net/anime/producer/11/Madhouse',
          },
        ],
        genres: [
          {
            mal_id: 1,
            type: 'anime',
            name: 'Action',
            url: 'https://myanimelist.net/anime/genre/1/Action',
          },
          {
            mal_id: 2,
            type: 'anime',
            name: 'Adventure',
            url: 'https://myanimelist.net/anime/genre/2/Adventure',
          },
          {
            mal_id: 10,
            type: 'anime',
            name: 'Fantasy',
            url: 'https://myanimelist.net/anime/genre/10/Fantasy',
          },
        ],
        explicit_genres: [],
        themes: [],
        demographics: [
          {
            mal_id: 27,
            type: 'anime',
            name: 'Shounen',
            url: 'https://myanimelist.net/anime/genre/27/Shounen',
          },
        ],
      },
      {
        mal_id: 42938,
        url: 'https://myanimelist.net/anime/42938/Fruits_Basket__The_Final',
        images: {
          jpg: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1085/114792.jpg',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1085/114792t.jpg',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1085/114792l.jpg',
          },
          webp: {
            image_url: 'https://cdn.myanimelist.net/images/anime/1085/114792.webp',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/1085/114792t.webp',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/1085/114792l.webp',
          },
        },
        trailer: {
          youtube_id: 'Ip8Btv2t_6c',
          url: 'https://www.youtube.com/watch?v=Ip8Btv2t_6c',
          embed_url: 'https://www.youtube.com/embed/Ip8Btv2t_6c?enablejsapi=1&wmode=opaque&autoplay=1',
          images: {
            image_url: 'https://img.youtube.com/vi/Ip8Btv2t_6c/default.jpg',
            small_image_url: 'https://img.youtube.com/vi/Ip8Btv2t_6c/sddefault.jpg',
            medium_image_url: 'https://img.youtube.com/vi/Ip8Btv2t_6c/mqdefault.jpg',
            large_image_url: 'https://img.youtube.com/vi/Ip8Btv2t_6c/hqdefault.jpg',
            maximum_image_url: 'https://img.youtube.com/vi/Ip8Btv2t_6c/maxresdefault.jpg',
          },
        },
        title: 'Fruits Basket: The Final',
        title_english: 'Fruits Basket: The Final Season',
        title_japanese: 'フルーツバスケット The Final',
        title_synonyms: [
          'Fruits Basket 3rd Season',
          'Fruits Basket (2019) 3rd Season',
          'Furuba',
        ],
        type: 'TV',
        source: 'Manga',
        episodes: 13,
        status: 'Finished Airing',
        airing: false,
        aired: {
          from: '2021-04-06T00:00:00+00:00',
          to: '2021-06-29T00:00:00+00:00',
          prop: {
            from: {
              day: 6,
              month: 4,
              year: 2021,
            },
            to: {
              day: 29,
              month: 6,
              year: 2021,
            },
          },
          string: 'Apr 6, 2021 to Jun 29, 2021',
        },
        duration: '23 min per ep',
        rating: 'PG-13 - Teens 13 or older',
        score: 9.04,
        scored_by: 163571,
        rank: 9,
        popularity: 547,
        members: 341129,
        favorites: 15764,
        synopsis: 'Hundreds of years ago, the Chinese Zodiac spirits and their god swore to stay together eternally. United by this promise, the possessed members of the Souma family shall always return to each other under any circumstances. Yet, when these bonds shackle them from freedom, it becomes an undesirable burden—a curse. As head of the clan, Akito is convinced that he shares a special connection with the other Soumas. While he desperately clings to this fantasy, the rest of the family remains isolated and suppressed by the fear of punishment. Tooru Honda, who has grown attached to the Soumas, is determined to break the chains that bind them. Her companionship with the family and her friends encourages her to move forward with lifting the curse. However, due to confounding revelations, she struggles to find the tenacity to continue her endeavors. With time slowly withering away, Tooru contends with an uncertain future in hopes of reaching the tranquility that may lie beyond all this commotion. [Written by MAL Rewrite]',
        background: null,
        season: 'spring',
        year: 2021,
        broadcast: {
          day: 'Tuesdays',
          time: '01:30',
          timezone: 'Asia/Tokyo',
          string: 'Tuesdays at 01:30 (JST)',
        },
        producers: [
          {
            mal_id: 16,
            type: 'anime',
            name: 'TV Tokyo',
            url: 'https://myanimelist.net/anime/producer/16/TV_Tokyo',
          },
          {
            mal_id: 100,
            type: 'anime',
            name: 'TV Osaka',
            url: 'https://myanimelist.net/anime/producer/100/TV_Osaka',
          },
          {
            mal_id: 139,
            type: 'anime',
            name: 'Nihon Ad Systems',
            url: 'https://myanimelist.net/anime/producer/139/Nihon_Ad_Systems',
          },
          {
            mal_id: 148,
            type: 'anime',
            name: 'Hakusensha',
            url: 'https://myanimelist.net/anime/producer/148/Hakusensha',
          },
          {
            mal_id: 1284,
            type: 'anime',
            name: 'Avex Pictures',
            url: 'https://myanimelist.net/anime/producer/1284/Avex_Pictures',
          },
          {
            mal_id: 2174,
            type: 'anime',
            name: 'TMS Music',
            url: 'https://myanimelist.net/anime/producer/2174/TMS_Music',
          },
        ],
        licensors: [
          {
            mal_id: 102,
            type: 'anime',
            name: 'Funimation',
            url: 'https://myanimelist.net/anime/producer/102/Funimation',
          },
        ],
        studios: [
          {
            mal_id: 73,
            type: 'anime',
            name: 'TMS Entertainment',
            url: 'https://myanimelist.net/anime/producer/73/TMS_Entertainment',
          },
        ],
        genres: [
          {
            mal_id: 8,
            type: 'anime',
            name: 'Drama',
            url: 'https://myanimelist.net/anime/genre/8/Drama',
          },
          {
            mal_id: 22,
            type: 'anime',
            name: 'Romance',
            url: 'https://myanimelist.net/anime/genre/22/Romance',
          },
          {
            mal_id: 37,
            type: 'anime',
            name: 'Supernatural',
            url: 'https://myanimelist.net/anime/genre/37/Supernatural',
          },
        ],
        explicit_genres: [],
        themes: [],
        demographics: [
          {
            mal_id: 25,
            type: 'anime',
            name: 'Shoujo',
            url: 'https://myanimelist.net/anime/genre/25/Shoujo',
          },
        ],
      },
      {
        mal_id: 15417,
        url: 'https://myanimelist.net/anime/15417/Gintama__Enchousen',
        images: {
          jpg: {
            image_url: 'https://cdn.myanimelist.net/images/anime/6/75172.jpg',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/6/75172t.jpg',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/6/75172l.jpg',
          },
          webp: {
            image_url: 'https://cdn.myanimelist.net/images/anime/6/75172.webp',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/6/75172t.webp',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/6/75172l.webp',
          },
        },
        trailer: {
          youtube_id: null,
          url: null,
          embed_url: null,
          images: {
            image_url: null,
            small_image_url: null,
            medium_image_url: null,
            large_image_url: null,
            maximum_image_url: null,
          },
        },
        title: "Gintama': Enchousen",
        title_english: 'Gintama: Enchousen',
        title_japanese: "銀魂' 延長戦",
        title_synonyms: [
          "Gintama' (2012)",
          "Gintama' Overdrive",
          'Kintama',
        ],
        type: 'TV',
        source: 'Manga',
        episodes: 13,
        status: 'Finished Airing',
        airing: false,
        aired: {
          from: '2012-10-04T00:00:00+00:00',
          to: '2013-03-28T00:00:00+00:00',
          prop: {
            from: {
              day: 4,
              month: 10,
              year: 2012,
            },
            to: {
              day: 28,
              month: 3,
              year: 2013,
            },
          },
          string: 'Oct 4, 2012 to Mar 28, 2013',
        },
        duration: '24 min per ep',
        rating: 'PG-13 - Teens 13 or older',
        score: 9.04,
        scored_by: 143748,
        rank: 10,
        popularity: 696,
        members: 279426,
        favorites: 2726,
        synopsis: "While Gintoki Sakata was away, the Yorozuya found themselves a new leader: Kintoki, Gintoki's golden-haired doppelganger. In order to regain his former position, Gintoki will need the help of those around him, a troubling feat when no one can remember him! Between Kintoki and Gintoki, who will claim the throne as the main character? In addition, Yorozuya make a trip back down to red-light district of Yoshiwara to aid an elderly courtesan in her search for her long-lost lover. Although the district is no longer in chains beneath the earth's surface, the trio soon learn of the tragic backstories of Yoshiwara's inhabitants that still haunt them. With flashback after flashback, this quest has Yorozuya witnessing everlasting love and protecting it as best they can with their hearts and souls. Gintama': Enchousen includes moments of action-packed intensity along with their usual lighthearted, slapstick humor for Gintoki and his friends. [Written by MAL Rewrite]",
        background: 'This is a third season of Gintama. In the episode continuity corresponds to episodes 253-265 of Gintama.',
        season: 'fall',
        year: 2012,
        broadcast: {
          day: 'Thursdays',
          time: '18:00',
          timezone: 'Asia/Tokyo',
          string: 'Thursdays at 18:00 (JST)',
        },
        producers: [
          {
            mal_id: 16,
            type: 'anime',
            name: 'TV Tokyo',
            url: 'https://myanimelist.net/anime/producer/16/TV_Tokyo',
          },
          {
            mal_id: 17,
            type: 'anime',
            name: 'Aniplex',
            url: 'https://myanimelist.net/anime/producer/17/Aniplex',
          },
          {
            mal_id: 53,
            type: 'anime',
            name: 'Dentsu',
            url: 'https://myanimelist.net/anime/producer/53/Dentsu',
          },
          {
            mal_id: 1365,
            type: 'anime',
            name: 'Shueisha',
            url: 'https://myanimelist.net/anime/producer/1365/Shueisha',
          },
          {
            mal_id: 1406,
            type: 'anime',
            name: 'Miracle Bus',
            url: 'https://myanimelist.net/anime/producer/1406/Miracle_Bus',
          },
        ],
        licensors: [],
        studios: [
          {
            mal_id: 14,
            type: 'anime',
            name: 'Sunrise',
            url: 'https://myanimelist.net/anime/producer/14/Sunrise',
          },
        ],
        genres: [
          {
            mal_id: 1,
            type: 'anime',
            name: 'Action',
            url: 'https://myanimelist.net/anime/genre/1/Action',
          },
          {
            mal_id: 4,
            type: 'anime',
            name: 'Comedy',
            url: 'https://myanimelist.net/anime/genre/4/Comedy',
          },
          {
            mal_id: 24,
            type: 'anime',
            name: 'Sci-Fi',
            url: 'https://myanimelist.net/anime/genre/24/Sci-Fi',
          },
        ],
        explicit_genres: [],
        themes: [
          {
            mal_id: 57,
            type: 'anime',
            name: 'Gag Humor',
            url: 'https://myanimelist.net/anime/genre/57/Gag_Humor',
          },
          {
            mal_id: 13,
            type: 'anime',
            name: 'Historical',
            url: 'https://myanimelist.net/anime/genre/13/Historical',
          },
          {
            mal_id: 20,
            type: 'anime',
            name: 'Parody',
            url: 'https://myanimelist.net/anime/genre/20/Parody',
          },
          {
            mal_id: 21,
            type: 'anime',
            name: 'Samurai',
            url: 'https://myanimelist.net/anime/genre/21/Samurai',
          },
        ],
        demographics: [
          {
            mal_id: 27,
            type: 'anime',
            name: 'Shounen',
            url: 'https://myanimelist.net/anime/genre/27/Shounen',
          },
        ],
      },
      {
        mal_id: 820,
        url: 'https://myanimelist.net/anime/820/Ginga_Eiyuu_Densetsu',
        images: {
          jpg: {
            image_url: 'https://cdn.myanimelist.net/images/anime/13/13225.jpg',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/13/13225t.jpg',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/13/13225l.jpg',
          },
          webp: {
            image_url: 'https://cdn.myanimelist.net/images/anime/13/13225.webp',
            small_image_url: 'https://cdn.myanimelist.net/images/anime/13/13225t.webp',
            large_image_url: 'https://cdn.myanimelist.net/images/anime/13/13225l.webp',
          },
        },
        trailer: {
          youtube_id: 'G7grjXe2Eyo',
          url: 'https://www.youtube.com/watch?v=G7grjXe2Eyo',
          embed_url: 'https://www.youtube.com/embed/G7grjXe2Eyo?enablejsapi=1&wmode=opaque&autoplay=1',
          images: {
            image_url: 'https://img.youtube.com/vi/G7grjXe2Eyo/default.jpg',
            small_image_url: 'https://img.youtube.com/vi/G7grjXe2Eyo/sddefault.jpg',
            medium_image_url: 'https://img.youtube.com/vi/G7grjXe2Eyo/mqdefault.jpg',
            large_image_url: 'https://img.youtube.com/vi/G7grjXe2Eyo/hqdefault.jpg',
            maximum_image_url: 'https://img.youtube.com/vi/G7grjXe2Eyo/maxresdefault.jpg',
          },
        },
        title: 'Ginga Eiyuu Densetsu',
        title_english: 'Legend of the Galactic Heroes',
        title_japanese: '銀河英雄伝説',
        title_synonyms: [
          'LoGH',
          'LotGH',
          "Gin'eiden",
          'GinEiDen',
          'Heldensagen Vom Kosmosinsel',
        ],
        type: 'OVA',
        source: 'Novel',
        episodes: 110,
        status: 'Finished Airing',
        airing: false,
        aired: {
          from: '1988-01-08T00:00:00+00:00',
          to: '1997-03-17T00:00:00+00:00',
          prop: {
            from: {
              day: 8,
              month: 1,
              year: 1988,
            },
            to: {
              day: 17,
              month: 3,
              year: 1997,
            },
          },
          string: 'Jan 8, 1988 to Mar 17, 1997',
        },
        duration: '26 min per ep',
        rating: 'R - 17+ (violence & profanity)',
        score: 9.03,
        scored_by: 69676,
        rank: 11,
        popularity: 700,
        members: 278282,
        favorites: 14499,
        synopsis: "The 150-year-long stalemate between the two interstellar superpowers, the Galactic Empire and the Free Planets Alliance, comes to an end when a new generation of leaders arises: the idealistic military genius Reinhard von Lohengramm, and the FPA's reserved historian, Yang Wenli. While Reinhard climbs the ranks of the Empire with the aid of his childhood friend, Siegfried Kircheis, he must fight not only the war, but also the remnants of the crumbling Goldenbaum Dynasty in order to free his sister from the Kaiser and unify humanity under one genuine ruler. Meanwhile, on the other side of the galaxy, Yang—a strong supporter of democratic ideals—has to stand firm in his beliefs, despite the struggles of the FPA, and show his pupil, Julian Mintz, that autocracy is not the solution. As ideologies clash amidst the war's many casualties, the two strategic masterminds must ask themselves what the real reason behind their battle is. [Written by MAL Rewrite]",
        background: 'Legend of the Galactic Heroes was adapted from a series of ten novels, published 1982–87, by Yoshiki Tanaka. The novels won the Seiun Award for the best long-form Japanese science fiction in 1988. At the start of its production the anime was distributed through a subscription system in which episodes were mailed to existing fans of the novels. It was made in four separate tranches over nearly a decade, with the production of side-stories continuing for several further years. The main series has the largest voice cast of any anime, with well over 300 voice actors, and it is the longest OVA series ever made. The novels have also been adapted into a manga, a stage musical by the Takarazuka Revue and a number of games.',
        season: null,
        year: null,
        broadcast: {
          day: null,
          time: null,
          timezone: null,
          string: null,
        },
        producers: [
          {
            mal_id: 16,
            type: 'anime',
            name: 'TV Tokyo',
            url: 'https://myanimelist.net/anime/producer/16/TV_Tokyo',
          },
          {
            mal_id: 99,
            type: 'anime',
            name: 'Kitty Films',
            url: 'https://myanimelist.net/anime/producer/99/Kitty_Films',
          },
          {
            mal_id: 382,
            type: 'anime',
            name: 'Tokuma Shoten',
            url: 'https://myanimelist.net/anime/producer/382/Tokuma_Shoten',
          },
          {
            mal_id: 1493,
            type: 'anime',
            name: 'Tokuma Japan Communications',
            url: 'https://myanimelist.net/anime/producer/1493/Tokuma_Japan_Communications',
          },
          {
            mal_id: 2434,
            type: 'anime',
            name: 'Wright Staff',
            url: 'https://myanimelist.net/anime/producer/2434/Wright_Staff',
          },
        ],
        licensors: [
          {
            mal_id: 376,
            type: 'anime',
            name: 'Sentai Filmworks',
            url: 'https://myanimelist.net/anime/producer/376/Sentai_Filmworks',
          },
        ],
        studios: [
          {
            mal_id: 1269,
            type: 'anime',
            name: 'K-Factory',
            url: 'https://myanimelist.net/anime/producer/1269/K-Factory',
          },
          {
            mal_id: 2256,
            type: 'anime',
            name: 'Kitty Film Mitaka Studio',
            url: 'https://myanimelist.net/anime/producer/2256/Kitty_Film_Mitaka_Studio',
          },
        ],
        genres: [
          {
            mal_id: 8,
            type: 'anime',
            name: 'Drama',
            url: 'https://myanimelist.net/anime/genre/8/Drama',
          },
          {
            mal_id: 24,
            type: 'anime',
            name: 'Sci-Fi',
            url: 'https://myanimelist.net/anime/genre/24/Sci-Fi',
          },
        ],
        explicit_genres: [],
        themes: [
          {
            mal_id: 50,
            type: 'anime',
            name: 'Adult Cast',
            url: 'https://myanimelist.net/anime/genre/50/Adult_Cast',
          },
          {
            mal_id: 38,
            type: 'anime',
            name: 'Military',
            url: 'https://myanimelist.net/anime/genre/38/Military',
          },
          {
            mal_id: 29,
            type: 'anime',
            name: 'Space',
            url: 'https://myanimelist.net/anime/genre/29/Space',
          },
        ],
        demographics: [],
      },
    ];
  }

  getTopAnime = async () => new Promise((resolve, reject) => {
    process.nextTick(() => {
      resolve(this.animes);
    });
  });
}

export default new AnimeServices();
